version: 2
jobs:
  build:
    docker:
      - image: codesimple/elm:0.19

    steps:
      - checkout

      - run:
          name: elm-memory-build
          command: elm-make src/Memory.elm

      - run:
          name: Print the Current Time
          command: date
